### ISSUE TITLE
_settings.scss is not watched and not compiled

### ISSUE THREAD

**Issue by ItIsInspiring** [schikulski/Gromf#31]
Hi,
thanks for sharing this efficient and usefull repository for wordpress.

I have a problem : the files .scss of Foundation in the bower_components are not watched and so not compiled everytime i make a change and save it.

i tried to change my gulpfile.js with the code i found on the official foundation 5 page :

gulp.src('./scss/*.scss')
  .pipe(sass({
    includePaths: ['bower_components/foundation/scss']
  }))
  .pipe(gulp.dest('./css')); 

But it doesn't work.
Could you help me ?
Thanks

**Comment by mAAdhaTTah** [comment]
Can you share the watch task you're using?

**Comment by ItIsInspiring** [comment]
i am using the default gulpfile.js contained in Gromf

**Comment by mAAdhaTTah** [comment]
Ok, so two things:

1. Don't modify the source in `bower_components` directly; copy the `_settings.scss` file out and commit it directly to the repo.
2. The [watch task](https://github.com/schikulski/Gromf/blob/master/gulpfile.js#L249-L263) will only fire based on changes to the globbed paths (the first param in array of paths to watch). You'll notice the `bower_components` folder isn't included there, which is why it isn't firing.

**Comment by ItIsInspiring** [comment]
Thanks for your answer.
Do you mean to copy the "_settings.scss" file in the "assets/styles" folder ?

**Comment by mAAdhaTTah** [comment]
Yeah, though I'd probably put it in `common`. Also make sure it's imported in `main.scss`.

**Comment by ItIsInspiring** [comment]
it works ! 
THANK YOU !
d–(^ ‿ ^ )z
